### PR TITLE
Handle network errors

### PR DESCRIPTION
**Pull request by sergej-tschak**
- add ability to react properly on network errors, such as lost of connection for example
- improvement of type checks for error responses with specific nesting of error information

### CODE REVIEW

**Comment by benj56** [comment]
I believe the approach we currently have where we try to figure out later with type guards what was actually passed in as payload isn't good. We have full control over the payload type, so let's enforce something consistent such as:

``` typescript
export type ErrorFormat = {type: 'error', error: Error } | {type: 'unsuccessfulApiResponse', response: ApiResponseOnFailure};
``` 
Then, in the reducer, `switch` can be used with the full benefit of the discriminated union and exhaustiveness check:
``` typescript
receiveError: (state, action: PayloadAction<ErrorFormat>) => {
      switch (action.payload.type) {
      case "error": { throw new Error('Not implemented yet: "error" case') }
      case "unsuccessfulApiResponse": { throw new Error('Not implemented yet: "unsuccessfulApiResponse" case') }
      }
    }
```

Then, no more type guards are necessary. Let's discuss tomorrow in the meeting with @whosshell

**Review by benj56 — CHANGES_REQUESTED** [review]
left comment

**Comment by sergej-tschak** [comment]
@benj56 let's take a look tomorrow all together. for me the biggest disadvantage of the approach when we provide type of error with payload itself is that in this case we need to modify plenty of epics. now we can just blindly path error to the one action and decide there what type of error it is.

**Comment by sergej-tschak** [comment]
This PR is closed as the way how we handle errors will be refactored.

**Pull request closed without merging**
